# CairnReactNative.podspec — iOS TurboModule pod for @cairn/react-native.
#
# MINIMAL (slice 1): just enough for RN autolinking + @react-native/codegen to
# emit the NativeCairnSpec Obj-C protocol at `pod install`. The vendored
# cairn_swift xcframework + Swift TurboModule source are layered in slice 2
# (after inspecting the generated NativeCairnSpec.h so the Swift impl matches the
# exact codegen contract). See docs/plans/cairn-rn-ios-turbomodule-2026-08-03.md.
Pod::Spec.new do |s|
  s.name         = "CairnReactNative"
  s.version      = "0.1.0"
  s.summary      = "Cairn local-first sync — React Native Codegen TurboModule over cairn-swift UniFFI."
  s.description  = "React Native facade over cairn-swift / cairn-kotlin UniFFI bindings."
  s.license      = "Apache-2.0"
  s.homepage     = "https://github.com/unfazed-dev/cairn"
  s.author       = { "unfazed-dev" => "https://github.com/unfazed-dev" }
  s.source       = { :git => "https://github.com/unfazed-dev/cairn", :tag => "#{s.version}" }

  s.platforms    = { :ios => "15.1" }
  s.swift_version = "5.0"

  # SELF-CONTAINED BUILD: at `pod install`, build the cairn-swift iOS staticlib
  # (fat arm64-sim + x86_64-sim) + copy the UniFFI Swift sources + generate the
  # cairn_swiftFFI modulemap INTO ios/. The ios/{cairn_swift.swift, ffi/*,
  # libcairn_swift.a} artifacts are gitignored REGEN OUTPUTS (not committed) —
  # this prepare_command is what makes a fresh checkout + `pod install` produce
  # a working pod, with no pre-vendored binaries shipped in the repo. Requires
  # the Rust toolchain + the `aarch64-apple-ios-sim` + `x86_64-apple-ios`
  # targets installed. ponytail: CAIRN_PROFILE=debug by default (fast; links
  # into a release app fine); set CAIRN_PROFILE=release for a shippable binary.
  # Upgrade path: a pre-built xcframework downloaded as a release artifact
  # (removes the Rust-toolchain requirement from consumers).
  s.prepare_command = "bash scripts/build-ios-staticlib.sh"

  # cairn_swift.swift + the TurboModule sources. cairn_swiftFFI.h lives in
  # ios/ffi/ (NOT a source header) so it can't collide with the framework's
  # umbrella modulemap — it's exposed as its own module via the modulemap below.
  s.source_files = "ios/*.{swift,m,mm}"
  s.preserve_paths = "ios/ffi/cairn_swiftFFI.h", "ios/ffi/cairn_swiftFFI.modulemap"

  # cairn_swift UniFFI bindings: the fat ios-sim staticlib + Swift marshalling
  # (cairn_swift.swift) + the C FFI module, all regenerated by the
  # prepare_command above. CairnReactNative builds as a FRAMEWORK (RN 0.86
  # default), where Swift bridging headers are unsupported — so cairn_swiftFFI
  # is exposed as a real module instead: a modulemap in ios/ffi/ found via
  # -fmodule-map-file makes canImport(cairn_swiftFFI) true, so cairn_swift.swift's
  # `import cairn_swiftFFI` resolves (the Xcode-16+/Swift-6 UniFFI-in-a-module
  # gotcha).
  s.vendored_libraries = "ios/libcairn_swift.a"
  s.frameworks = "Security", "CoreFoundation", "Foundation"
  s.libraries = "resolv"
  s.pod_target_xcconfig = {
    "HEADER_SEARCH_PATHS" => "$(PODS_TARGET_SRCROOT)/ios/ffi",
    "OTHER_SWIFT_FLAGS" => "-Xcc -fmodule-map-file=$(PODS_TARGET_SRCROOT)/ios/ffi/cairn_swiftFFI.modulemap",
  }

  # Wires React-Core + the @react-native/codegen-generated `NativeCairnSpec.h`
  # (emitted at `pod install` now that package.json declares `codegenConfig` —
  # type "modules" = TurboModule). The Swift impl in ios/ conforms to that
  # Obj-C protocol. See docs/plans/cairn-rn-ios-turbomodule-2026-08-03.md.
  install_modules_dependencies(s)
end
