// GENERATED by `cairn gen` — do not edit. Regenerate with `cairn pull && cairn gen`.
import 'package:cairn_flutter/cairn_flutter.dart';

const cairnConfig = CairnConfig(
  url: 'ws://127.0.0.1:8800/sync',
);

const cairnSchema = CairnSchema(tables: [
  CairnTable(name: 'tasks', primaryKey: ['id'], columns: [
    CairnColumn.text('id'),
    CairnColumn.text('org_id'),
    CairnColumn.text('assignee_id'),
    CairnColumn.text('title'),
    CairnColumn.integer('completed'),
    CairnColumn.text('created_at'),
    CairnColumn.text('updated_at'),
  ]),
  CairnTable(name: 'providers', primaryKey: ['id'], columns: [
    CairnColumn.text('id'),
    CairnColumn.text('name'),
    CairnColumn.text('specialty'),
    CairnColumn.text('email'),
    CairnColumn.text('phone'),
    CairnColumn.text('created_at'),
  ]),
  CairnTable(name: 'clients', primaryKey: ['id'], columns: [
    CairnColumn.text('id'),
    CairnColumn.text('name'),
    CairnColumn.text('email'),
    CairnColumn.text('phone'),
    CairnColumn.text('notes'),
    CairnColumn.text('created_at'),
  ]),
  CairnTable(name: 'availabilities', primaryKey: ['id'], columns: [
    CairnColumn.text('id'),
    CairnColumn.text('provider_id'),
    CairnColumn.integer('weekday'),
    CairnColumn.integer('start_min'),
    CairnColumn.integer('end_min'),
  ]),
  CairnTable(name: 'appointments', primaryKey: ['id'], columns: [
    CairnColumn.text('id'),
    CairnColumn.text('provider_id'),
    CairnColumn.text('client_id'),
    CairnColumn.text('starts_at'),
    CairnColumn.integer('duration_min'),
    CairnColumn.text('status'),
    CairnColumn.text('notes'),
    CairnColumn.text('created_at'),
  ]),
  CairnTable(name: 'invoices', primaryKey: ['id'], columns: [
    CairnColumn.text('id'),
    CairnColumn.text('appointment_id'),
    CairnColumn.text('client_id'),
    CairnColumn.integer('amount_cents'),
    CairnColumn.text('status'),
    CairnColumn.text('issued_at'),
    CairnColumn.text('created_at'),
  ]),
]);

class Task {
  const Task({required this.id, this.orgId, this.assigneeId, this.title, this.completed, this.createdAt, this.updatedAt});
  final String id;
  final String? orgId;
  final String? assigneeId;
  final String? title;
  final int? completed;
  final String? createdAt;
  final String? updatedAt;

  factory Task.fromRow(Map<String, dynamic> r) => Task(
    id: (r['_pk'] ?? r['id']).toString(),
    orgId: r['org_id']?.toString(),
    assigneeId: r['assignee_id']?.toString(),
    title: r['title']?.toString(),
    completed: r['completed'] is int ? r['completed'] : int.tryParse('${r['completed']}'),
    createdAt: r['created_at']?.toString(),
    updatedAt: r['updated_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'org_id': orgId,
    'assignee_id': assigneeId,
    'title': title,
    'completed': completed,
    'created_at': createdAt,
    'updated_at': updatedAt,
  };
}

class Provider {
  const Provider({required this.id, this.name, this.specialty, this.email, this.phone, this.createdAt});
  final String id;
  final String? name;
  final String? specialty;
  final String? email;
  final String? phone;
  final String? createdAt;

  factory Provider.fromRow(Map<String, dynamic> r) => Provider(
    id: (r['_pk'] ?? r['id']).toString(),
    name: r['name']?.toString(),
    specialty: r['specialty']?.toString(),
    email: r['email']?.toString(),
    phone: r['phone']?.toString(),
    createdAt: r['created_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'name': name,
    'specialty': specialty,
    'email': email,
    'phone': phone,
    'created_at': createdAt,
  };
}

class Client {
  const Client({required this.id, this.name, this.email, this.phone, this.notes, this.createdAt});
  final String id;
  final String? name;
  final String? email;
  final String? phone;
  final String? notes;
  final String? createdAt;

  factory Client.fromRow(Map<String, dynamic> r) => Client(
    id: (r['_pk'] ?? r['id']).toString(),
    name: r['name']?.toString(),
    email: r['email']?.toString(),
    phone: r['phone']?.toString(),
    notes: r['notes']?.toString(),
    createdAt: r['created_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'name': name,
    'email': email,
    'phone': phone,
    'notes': notes,
    'created_at': createdAt,
  };
}

class Availability {
  const Availability({required this.id, this.providerId, this.weekday, this.startMin, this.endMin});
  final String id;
  final String? providerId;
  final int? weekday;
  final int? startMin;
  final int? endMin;

  factory Availability.fromRow(Map<String, dynamic> r) => Availability(
    id: (r['_pk'] ?? r['id']).toString(),
    providerId: r['provider_id']?.toString(),
    weekday: r['weekday'] is int ? r['weekday'] : int.tryParse('${r['weekday']}'),
    startMin: r['start_min'] is int ? r['start_min'] : int.tryParse('${r['start_min']}'),
    endMin: r['end_min'] is int ? r['end_min'] : int.tryParse('${r['end_min']}'),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'provider_id': providerId,
    'weekday': weekday,
    'start_min': startMin,
    'end_min': endMin,
  };
}

class Appointment {
  const Appointment({required this.id, this.providerId, this.clientId, this.startsAt, this.durationMin, this.status, this.notes, this.createdAt});
  final String id;
  final String? providerId;
  final String? clientId;
  final String? startsAt;
  final int? durationMin;
  final String? status;
  final String? notes;
  final String? createdAt;

  factory Appointment.fromRow(Map<String, dynamic> r) => Appointment(
    id: (r['_pk'] ?? r['id']).toString(),
    providerId: r['provider_id']?.toString(),
    clientId: r['client_id']?.toString(),
    startsAt: r['starts_at']?.toString(),
    durationMin: r['duration_min'] is int ? r['duration_min'] : int.tryParse('${r['duration_min']}'),
    status: r['status']?.toString(),
    notes: r['notes']?.toString(),
    createdAt: r['created_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'provider_id': providerId,
    'client_id': clientId,
    'starts_at': startsAt,
    'duration_min': durationMin,
    'status': status,
    'notes': notes,
    'created_at': createdAt,
  };
}

class Invoice {
  const Invoice({required this.id, this.appointmentId, this.clientId, this.amountCents, this.status, this.issuedAt, this.createdAt});
  final String id;
  final String? appointmentId;
  final String? clientId;
  final int? amountCents;
  final String? status;
  final String? issuedAt;
  final String? createdAt;

  factory Invoice.fromRow(Map<String, dynamic> r) => Invoice(
    id: (r['_pk'] ?? r['id']).toString(),
    appointmentId: r['appointment_id']?.toString(),
    clientId: r['client_id']?.toString(),
    amountCents: r['amount_cents'] is int ? r['amount_cents'] : int.tryParse('${r['amount_cents']}'),
    status: r['status']?.toString(),
    issuedAt: r['issued_at']?.toString(),
    createdAt: r['created_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'appointment_id': appointmentId,
    'client_id': clientId,
    'amount_cents': amountCents,
    'status': status,
    'issued_at': issuedAt,
    'created_at': createdAt,
  };
}

