#!/usr/bin/env bash
# build-android.sh — cross-compile libcairn_kotlin.so + regenerate UniFFI Kotlin
# sources + strip + copy into the RN module's android project.
#
# Adapted from sdk/cairn_kotlin/scripts/run-live-e2e.sh steps 1-3. The RN
# module REUSES sdk/cairn_kotlin wholesale — same .so, same UniFFI bindings —
# so this script drives the SAME cargo + uniffi-bindgen commands, just with the
# outputs routed into cairn_react_native/android/ instead of cairn_kotlin/android/.
#
# After this script, `cd android && ANDROID_SERIAL=emulator-5556 ./gradlew
# connectedDebugAndroidTest` builds the test apk + runs the offline
# `offline_turbomodule_connect_query_roundTrip` instrumented test on the emulator.
#
# Usage: ./scripts/build-android.sh
# Exit codes: 0 = .so + Kotlin sources in place; non-zero = cargo/bindgen failed.
set -euo pipefail

CAIRN_RN="/Volumes/developer_ssd/Developer/cairn/sdk/cairn_react_native"
CAIRN_KT="/Volumes/developer_ssd/Developer/cairn/sdk/cairn_kotlin"
REPO_ROOT="/Volumes/developer_ssd/Developer/cairn"

NDK_VERSION="${CAIRN_NDK_VERSION:-28.2.13676358}"
NDK="$HOME/Library/Android/sdk/ndk/$NDK_VERSION"
ANDROID_SDK="$HOME/Library/Android/sdk"

# -------- 0. local.properties (machine-specific sdk.dir) -------------------
echo "[rn-build] 0/4 write android/local.properties"
cat > "$CAIRN_RN/android/local.properties" <<EOF
# Local Android SDK location (machine-specific — gitignored).
# Regenerated by scripts/build-android.sh if absent.
sdk.dir=$ANDROID_SDK
EOF

# -------- 1. cargo build --target aarch64-linux-android --------------------
echo "[rn-build] 1/4 cargo build --target aarch64-linux-android (cairn_kotlin)"
cd "$CAIRN_KT"
export ANDROID_NDK_HOME="$NDK"
export CC_aarch64_linux_android="$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android24-clang"
export AR_aarch64_linux_android="$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$CC_aarch64_linux_android"
cargo build --target aarch64-linux-android

# -------- 2. uniffi-bindgen generate (host .dylib → Kotlin sources) --------
echo "[rn-build] 2/4 uniffi-bindgen generate (Kotlin sources)"
cargo build --lib  # host .dylib for bindgen symbol read
# Route the generated Kotlin into the RN module's source set (NOT cairn_kotlin's),
# so cairn_kotlin stays untouched. build.gradle.kts adds `kotlin-uniffi` as a
# java.srcDir; the generated package is `uniffi.cairn_kotlin`, so the .kt lands
# at kotlin-uniffi/uniffi/cairn_kotlin/cairn_kotlin.kt.
#
# NOTE: cairn_kotlin has its OWN cargo target dir (sdk/cairn_kotlin/target/,
# NOT the workspace root) — the dylib + .so live there. Mirrors run-live-e2e.sh's
# relative-path references which work because it cd's into $CAIRN_KT first.
rm -rf "$CAIRN_RN/android/src/main/kotlin-uniffi"
uniffi-bindgen generate \
    --library "$CAIRN_KT/target/debug/libcairn_kotlin.dylib" \
    --language kotlin \
    --out-dir "$CAIRN_RN/android/src/main/kotlin-uniffi"

# -------- 3. strip + copy .so → jniLibs/arm64-v8a/ -------------------------
echo "[rn-build] 3/4 strip + copy .so → android/src/main/jniLibs/arm64-v8a/"
mkdir -p "$CAIRN_RN/android/src/main/jniLibs/arm64-v8a"
"$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip" --strip-debug \
    -o "$CAIRN_RN/android/src/main/jniLibs/arm64-v8a/libcairn_kotlin.so" \
    "$CAIRN_KT/target/aarch64-linux-android/debug/libcairn_kotlin.so"
ls -la "$CAIRN_RN/android/src/main/jniLibs/arm64-v8a/libcairn_kotlin.so"

# -------- 4. summary -------------------------------------------------------
echo "[rn-build] 4/4 done. Verify on emulator:"
echo "  cd $CAIRN_RN/android"
echo "  ANDROID_SERIAL=emulator-5556 ./gradlew connectedDebugAndroidTest --console=plain"
